# Generated by Django 3.2.7 on 2022-01-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zp', models.CharField(max_length=50, verbose_name='Заработная плата')),
                ('trebovan', models.CharField(max_length=500, verbose_name='Требования')),
                ('bonus', models.CharField(max_length=500, verbose_name='Бонусы')),
                ('navki', models.CharField(max_length=500, verbose_name='Навыки')),
                ('o_kompanii', models.CharField(max_length=1000, verbose_name='О кампании')),
                ('number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('special', models.CharField(max_length=100, verbose_name='Специальность')),
                ('date', models.CharField(max_length=500, verbose_name='Дата размещения')),
            ],
            options={
                'verbose_name': 'Вакансии вывод',
                'verbose_name_plural': 'Вакансии вывод',
            },
        ),
    ]
