# Generated by Django 3.2.6 on 2021-08-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otvet1', models.CharField(max_length=50, verbose_name='ФИО')),
                ('otvet2', models.CharField(max_length=5, verbose_name='Ответ 2')),
                ('otvet3', models.CharField(max_length=5, verbose_name='Ответ 3')),
                ('otvet4', models.CharField(max_length=5, verbose_name='Ответ 4')),
                ('otvet5', models.CharField(max_length=5, verbose_name='Ответ 5')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
    ]
