# Generated by Django 3.2.7 on 2022-01-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=50, verbose_name='Проживаете в городе/селе')),
                ('date', models.CharField(max_length=50, verbose_name='Дата рождения')),
                ('gender', models.CharField(max_length=10, verbose_name='Пол')),
                ('opat_rabot', models.CharField(max_length=100, verbose_name='Опыт работы')),
                ('special', models.CharField(max_length=100, verbose_name='Специальность')),
                ('o_sebe', models.CharField(max_length=500, verbose_name='О себе')),
                ('obrazov', models.CharField(max_length=50, verbose_name='Образование')),
                ('obraz_ucher', models.CharField(max_length=150, verbose_name='Образовательное учереждение')),
                ('leanguage', models.CharField(max_length=100, verbose_name='Языки')),
                ('komandirovka', models.CharField(max_length=50, verbose_name='Готовность к командировкам')),
                ('zanyatost', models.CharField(max_length=50, verbose_name='Занятость')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
