# Generated by Django 3.2.6 on 2021-08-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='НИК')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('password1', models.CharField(max_length=50, verbose_name='Пароль')),
                ('password2', models.CharField(max_length=50, verbose_name='Подтвердите пароль')),
                ('school_number', models.CharField(max_length=50, verbose_name='Название школы и №')),
                ('age', models.CharField(max_length=50, verbose_name='Возраст')),
                ('grade', models.CharField(max_length=50, verbose_name='Класс')),
                ('parenst', models.CharField(max_length=50, verbose_name='ФИО родителя')),
                ('number_parenst', models.CharField(max_length=50, verbose_name='Телефон родителя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
