# Generated by Django 3.2.7 on 2022-01-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Middle_name', models.CharField(max_length=100)),
                ('School', models.IntegerField()),
                ('Class', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
